CREATE TYPE "public"."edutrack_attendance_status" AS ENUM('present', 'absent', 'late', 'excused');--> statement-breakpoint
CREATE TYPE "public"."edutrack_grade_type" AS ENUM('quiz', 'assignment', 'exam', 'activity', 'project', 'final');--> statement-breakpoint
CREATE TYPE "public"."edutrack_notification_channel" AS ENUM('sms', 'in_app');--> statement-breakpoint
CREATE TYPE "public"."edutrack_user_role" AS ENUM('student', 'admin');--> statement-breakpoint
CREATE TABLE "edutrack_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "edutrack_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
ALTER TABLE "edutrack_account" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_announcement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_announcement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"body" text NOT NULL,
	"createdById" varchar(255),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edutrack_announcement" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_attendance" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_attendance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"studentId" varchar(255) NOT NULL,
	"date" date NOT NULL,
	"remarks" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"status" "edutrack_attendance_status" NOT NULL,
	"recordedById" varchar(255) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edutrack_attendance" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_class_room" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_class_room_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"adviserId" varchar(255),
	"gradeLevel" varchar(32),
	"schoolYear" varchar(32)
);
--> statement-breakpoint
ALTER TABLE "edutrack_class_room" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_grade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_grade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"studentId" varchar(255) NOT NULL,
	"subjectId" integer NOT NULL,
	"type" "edutrack_grade_type" NOT NULL,
	"label" varchar(128) NOT NULL,
	"score" double precision NOT NULL,
	"total" double precision NOT NULL,
	"quarter" integer,
	"remarks" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"recordedById" varchar(255) NOT NULL,
	CONSTRAINT "grade_score_valid" CHECK ("edutrack_grade"."score" >= 0 AND "edutrack_grade"."total" > 0 AND "edutrack_grade"."score" <= "edutrack_grade"."total"),
	CONSTRAINT "grade_quarter_valid" CHECK ("edutrack_grade"."quarter" BETWEEN 1 AND 4)
);
--> statement-breakpoint
ALTER TABLE "edutrack_grade" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"channel" "edutrack_notification_channel" DEFAULT 'in_app' NOT NULL,
	"message" text NOT NULL,
	"recipientId" varchar(255),
	"readAt" timestamp with time zone,
	"attendanceId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edutrack_notification" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edutrack_session" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_sms_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_sms_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"notificationId" integer NOT NULL,
	"toPhoneNumber" varchar(32) NOT NULL,
	"status" varchar(64) NOT NULL,
	"twilioSid" varchar(128),
	"errorMessage" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edutrack_sms_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_student" (
	"userId" varchar(255) PRIMARY KEY NOT NULL,
	"studentNumber" varchar(64) NOT NULL,
	"gradeLevel" varchar(32),
	"guardianName" varchar(255),
	"guardianPhone" varchar(32),
	"classRoomId" integer,
	CONSTRAINT "edutrack_student_studentNumber_unique" UNIQUE("studentNumber")
);
--> statement-breakpoint
ALTER TABLE "edutrack_student" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_subject" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_subject_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(128) NOT NULL,
	"classRoomId" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edutrack_subject" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"passwordHash" varchar(255),
	"role" "edutrack_user_role" DEFAULT 'student' NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "edutrack_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "edutrack_user" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "edutrack_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "edutrack_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "edutrack_verification_token" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "edutrack_account" ADD CONSTRAINT "edutrack_account_userId_edutrack_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_announcement" ADD CONSTRAINT "edutrack_announcement_createdById_edutrack_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_attendance" ADD CONSTRAINT "edutrack_attendance_studentId_edutrack_student_userId_fk" FOREIGN KEY ("studentId") REFERENCES "public"."edutrack_student"("userId") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_attendance" ADD CONSTRAINT "edutrack_attendance_recordedById_edutrack_user_id_fk" FOREIGN KEY ("recordedById") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_class_room" ADD CONSTRAINT "edutrack_class_room_adviserId_edutrack_user_id_fk" FOREIGN KEY ("adviserId") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_grade" ADD CONSTRAINT "edutrack_grade_studentId_edutrack_student_userId_fk" FOREIGN KEY ("studentId") REFERENCES "public"."edutrack_student"("userId") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_grade" ADD CONSTRAINT "edutrack_grade_subjectId_edutrack_subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."edutrack_subject"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_grade" ADD CONSTRAINT "edutrack_grade_recordedById_edutrack_user_id_fk" FOREIGN KEY ("recordedById") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_notification" ADD CONSTRAINT "edutrack_notification_recipientId_edutrack_user_id_fk" FOREIGN KEY ("recipientId") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_notification" ADD CONSTRAINT "edutrack_notification_attendanceId_edutrack_attendance_id_fk" FOREIGN KEY ("attendanceId") REFERENCES "public"."edutrack_attendance"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_session" ADD CONSTRAINT "edutrack_session_userId_edutrack_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_sms_log" ADD CONSTRAINT "edutrack_sms_log_notificationId_edutrack_notification_id_fk" FOREIGN KEY ("notificationId") REFERENCES "public"."edutrack_notification"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_student" ADD CONSTRAINT "edutrack_student_userId_edutrack_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."edutrack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_student" ADD CONSTRAINT "edutrack_student_classRoomId_edutrack_class_room_id_fk" FOREIGN KEY ("classRoomId") REFERENCES "public"."edutrack_class_room"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edutrack_subject" ADD CONSTRAINT "edutrack_subject_classRoomId_edutrack_class_room_id_fk" FOREIGN KEY ("classRoomId") REFERENCES "public"."edutrack_class_room"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "edutrack_account" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "attendance_student_date_idx" ON "edutrack_attendance" USING btree ("studentId","date");--> statement-breakpoint
CREATE INDEX "grade_student_subject_idx" ON "edutrack_grade" USING btree ("studentId","subjectId");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "edutrack_session" USING btree ("userId");