CREATE TABLE "edutrack_email_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edutrack_email_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"notificationId" integer NOT NULL,
	"toEmail" varchar(255) NOT NULL,
	"message" text NOT NULL,
	"status" varchar(64) DEFAULT 'pending' NOT NULL,
	"providerId" varchar(255),
	"errorMessage" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "edutrack_email_log_notificationId_unique" UNIQUE("notificationId")
);
--> statement-breakpoint
ALTER TABLE "edutrack_email_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "edutrack_student" ADD COLUMN "guardianEmail" varchar(255);--> statement-breakpoint
ALTER TABLE "edutrack_student" ADD COLUMN "guardianEmailConsent" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "edutrack_email_log" ADD CONSTRAINT "edutrack_email_log_notificationId_edutrack_notification_id_fk" FOREIGN KEY ("notificationId") REFERENCES "public"."edutrack_notification"("id") ON DELETE no action ON UPDATE no action;